"""Auto-generates docs/DATA_PROVENANCE.md from the harvested metadata. Never hand-edit that
file - rerun this script instead. Every accession, its sample counts by role, platform, and
the generation timestamp/git SHA are all pulled from real harvested data, not typed by hand.
"""

from __future__ import annotations

import subprocess
from datetime import datetime, timezone

import pandas as pd

from epigrade import paths
from epigrade.acquire.harmonize import harmonize
from epigrade.acquire.harvest import ACCESSIONS


def _git_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=paths.repo_root(), text=True,
        ).strip()
    except Exception:  # noqa: BLE001
        return "unknown"


def main() -> None:
    samples = pd.read_parquet(paths.interim_dir() / "samples.parquet")
    harmonized = harmonize(samples)

    lines = [
        "# Data Provenance",
        "",
        f"Auto-generated by `scripts/generate_provenance.py` at "
        f"{datetime.now(timezone.utc).isoformat()} from git `{_git_sha()}`. "
        "Do not hand-edit - rerun the script instead.",
        "",
        "All data below comes from public NCBI GEO accessions, harvested via GEOparse in "
        "`how=\"brief\"` mode (metadata only - see docs/METHODS.md for why).",
        "",
        f"## Accessions ({len(ACCESSIONS)})",
        "",
        "| Accession | Samples | Platform(s) | Roles present |",
        "|---|---|---|---|",
    ]

    for acc in sorted(ACCESSIONS):
        g = harmonized[harmonized.series_id == acc]
        if g.empty:
            lines.append(f"| {acc} | not harvested | - | - |")
            continue
        platforms = ", ".join(sorted(g["platform_id"].dropna().unique()))
        role_counts = g["role"].value_counts()
        roles_str = ", ".join(f"{role}={n}" for role, n in role_counts.items())
        lines.append(f"| {acc} | {len(g)} | {platforms} | {roles_str} |")

    lines += [
        "",
        f"**Total samples harvested**: {len(harmonized)}",
        "",
        "## Role definitions",
        "",
        "| Role | Meaning |",
        "|---|---|",
        "| case | Confirmed/diagnosed affected individual |",
        "| matched_control | Control specifically recruited for that disorder's study |",
        "| population_control | General population data, no disorder relevance |",
        "| unaffected_relative | Parent/sibling/relative of a case, not themselves diagnosed |",
        "| under_test | Variant of uncertain significance or explicitly-being-classified sample |",
        "| cell_line | Immortalized cell line (lymphoblastoid, etc.) |",
        "| wrong_tissue | Tissue mismatched from the rest of its study |",
        "| exclude_other | Anything else not pooled as a case or clean control |",
        "",
        "## Disorder case counts (role=case, in-scope disorders only)",
        "",
        "| Disorder | Cases | Studies |",
        "|---|---|---|",
    ]

    cases = harmonized[harmonized.role == "case"]
    for disorder, g in cases.groupby("disorder"):
        studies = ", ".join(sorted(g["series_id"].unique()))
        lines.append(f"| {disorder} | {len(g)} | {studies} |")

    lines += [
        "",
        "## External (non-GEO) data used",
        "",
        "| File | Source | Retrieved via |",
        "|---|---|---|",
        "| Choufani et al. 2015 Supplementary Data 3 (7,085-probe Sotos signature) | "
        "Nature Communications ncomms10207, PMC4703864 | Europe PMC supplementary-files API |",
        "| Choufani et al. 2015 Supplementary Data 7 (missense variant clinical table) | "
        "same as above | same as above |",
        "| Chen et al. 2013 cross-reactive probe list (29,233 probes) | "
        "Epigenetics 8:203-9, originally hosted at sickkids.ca (Weksberg lab) | "
        "Jfortin1/funnorm_repro GitHub mirror |",
    ]

    out_path = paths.repo_root() / "docs" / "DATA_PROVENANCE.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
